Repository onmetal/template-operator, pull requests merged in 2021-09, with the labels that each got.

#11 Added Helm chart
  charts/template-operator/.helmignore
  charts/template-operator/Chart.yaml
  charts/template-operator/crds
  charts/template-operator/templates/_helpers.tpl
  charts/template-operator/templates/deployment.yaml
  charts/template-operator/templates/hpa.yaml
  charts/template-operator/templates/leader_election_role.yaml
  charts/template-operator/templates/leader_election_role_binding.yaml
  charts/template-operator/templates/role.yaml
  charts/template-operator/templates/role_binding.yaml
  charts/template-operator/templates/service.yaml
  charts/template-operator/templates/serviceaccount.yaml
  charts/template-operator/values.yaml
Labels: size/L, helm

#13 Allow accessing template properties in template
  config/samples/template_v1alpha1_template.yaml
  controllers/template_controller.go
  controllers/template_controller_test.go
  main.go
Labels: enhancement, size/M

#12 Added installation instructions for helm chart
  README.md
Labels: documentation, size/S

#14 Use docker actions for image builds
  .github/workflows/publish-docker.yml
  controllers/template_controller.go
  kubectl-template_operator/main.go
Labels: size/M

#17 Fix latest docker tag
  .github/workflows/publish-docker.yml
Labels: size/XS, chore
